spring:
  datasource:
    username: root

  application:
    name: student-service

  # config server
  config:
    import: "optional:configserver:http://localhost:8888"

# eureka server config
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka